---
- name: add distribution-specific variables
  include_vars: "{{ ansible_distribution }}.yml"

- name: add Debian Wheezy workaround
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
  when: (ansible_distribution == "Debian") and (ansible_distribution_release == "wheezy")

- name: install unattended-upgrades
  apt:
    pkg: unattended-upgrades
    state: present
    cache_valid_time: "{{unattended_cache_valid_time}}"
    update_cache: yes

- name: install reboot dependencies
  include: reboot.yml
  when: unattended_automatic_reboot

- name: create APT auto-upgrades configuration
  template:
    src: auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 0644

- name: create unattended-upgrades configuration
  template:
    src: unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: 0644
    
- name: Ensure apt-listchanges emails the configured items
  ini_file:
    path: /etc/apt/listchanges.conf
    section: apt
    no_extra_spaces: true
    option: "{{ item.opt }}"
    value: "{{ item.val }}"
  with_items:
    - opt: email_address
      val: "{{ unattended_mail }}"
    - opt: which
      val: "{{ unattended_mail_listchanges_which }}"
  when:
    - unattended_mail != False
